apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
    spring-boot: "true"
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: auth-service
  type: ClusterIP