apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
      - name: auth-service
        image: khanhromvn/flowright_auth_service:latest
        ports:
        - containerPort: 8080