apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-service
  labels:
    app: member-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-service
  template:
    metadata:
      labels:
        app: member-service
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
      - name: member-service
        image: khanhromvn/flowright_member_service:latest
        ports:
        - containerPort: 8080