apiVersion: v1
kind: Service
metadata:
  name: member-service
  labels:
    app: member-service
    spring-boot: "true"
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: member-service
  type: ClusterIP