apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-service
  labels:
    app: project-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-service
  template:
    metadata:
      labels:
        app: project-service
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
      - name: project-service
        image: khanhromvn/flowright_project_service:latest
        ports:
        - containerPort: 8080