apiVersion: v1
kind: Service
metadata:
  name: project-service
  labels:
    app: project-service
    spring-boot: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: project-service