apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  labels:
    app: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
      - name: task-service
        image: khanhromvn/flowright_task_service:latest
        ports:
        - containerPort: 8080