apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-service
  labels:
    app: team-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-service
  template:
    metadata:
      labels:
        app: team-service
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
      - name: team-service
        image: khanhromvn/flowright_team_service:latest
        ports:
        - containerPort: 8080