apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-service
  labels:
    app: workspace-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace-service
  template:
    metadata:
      labels:
        app: workspace-service
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
      - name: workspace-service
        image: khanhromvn/flowright_workspace_service:latest
        ports:
        - containerPort: 8080